name: Deploy

env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

on:
  repository_dispatch:
    types:
      - winget-deploy

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup dotnet SDK v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Set path for candle and light from WixTools
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
        shell: bash
      - name: Generate Pulumi MSI
        run: dotnet run --project ./src -- generate msi
      - name: Setup dotnet SDK v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Push WinGet Manifest
        shell: powershell
        run: |
          $github_token = "${{ secrets.PULUMI_BOT_TOKEN }}"
          $downloadUrl = Get-Content -Path ./src/download-url.txt
          $version = Get-Content -Path ./src/version.txt

          $download_exists = Test-Path -Path ./src/download-url.txt -PathType Leaf
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          if ($download_exists) { .\wingetcreate.exe update Pulumi.Pulumi --urls $downloadUrl --version $version --token $github_token --submit }