on:
  repository_dispatch:
    types:
      - winget-deploy
jobs:
  deploy:
      runs-on: windows-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Pulumi Manifest for WinGet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        run: dotnet run --project ./src
      - name: Push WinGet Manifest
        shell: powershell
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe submit -t $(GITHUB_TOKEN) ./src/manifest.yaml