name: Deploy

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  repository_dispatch:
    types:
      - winget-deploy
jobs:
  deploy:
      runs-on: windows-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Install WixTools
        shell: powershell
        run: |
          choco install wixtoolset
      - name: Generate Pulumi manifest
        run: dotnet run --project ./src -- generate manifest
      - name: Push WinGet Manifest
        shell: powershell
        run: |
          $github_token = "${{ secrets.GITHUB_TOKEN }}"
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe submit -t $github_token ./src/manifest.yaml