name: Generate MSI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Install WixTools
        shell: powershell
        run: |
          choco install wixtoolset
      - name: Generate Pulumi MSI
        run: dotnet run --project ./src -- generate msi
